services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    environment:
      - PHX_HOST=localhost
      - PORT=4000
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=8OTycdB8pDM6KiieO8j1Jxn_Uszk6nKwgraq7hcFHW8
      - SECRET_KEY_BASE=VG9YwqbJGYc+H+8OeHg0RMnlKEHp5/YtLh3K0yRhGGwlqcHaVGxLnPZlPMwuqL+B4XiGpkOPqD+hGqnKwLgvig==
    depends_on:
      - meilisearch
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.11.3
    ports:
      - "0:7700"
    environment:
      - MEILI_MASTER_KEY=8OTycdB8pDM6KiieO8j1Jxn_Uszk6nKwgraq7hcFHW8
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  meili_data:
