services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=K8RlzyUWzk9v7LzX5m3nQ4JtHpYgVdFjBcNwM6qSsTvA2eGhPkXyDuW9aEoOiRxC
      - PHX_HOST=localhost
      - PORT=4000
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=-U1pIl8HGXtiN6YFprGPPHrreY236-XRaeXv-vgNIW0
    depends_on:
      - meilisearch
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=-U1pIl8HGXtiN6YFprGPPHrreY236-XRaeXv-vgNIW0
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

  livebook:
    image: ghcr.io/livebook-dev/livebook:latest
    ports:
      - "8080:8080"
    environment:
      - LIVEBOOK_PASSWORD=@Livesearchanalytics123
      - LIVEBOOK_PORT=8080
    depends_on:
      - app
    volumes:
      - ./notebooks:/data/notebooks
    restart: unless-stopped

volumes:
  meili_data:
